### ISSUE TITLE
output/downstream_analysis/MACS2/FILTER/seurat_obj.rds', probable reason 'No such file or directory'

### ISSUE THREAD

**Issue by yejg2017** [wbaopaul/scATAC-pro#12]
Hi！When I run clustering or downstream,I always got these error,and I don't know how to fixed it

**Comment by wbaopaul** [comment]
Can you post the log file for clustering, saved in output/logs/clustering.log? Thanks.

**Comment by yejg2017** [comment]
[clustering.log](https://github.com/wbaopaul/scATAC-pro/files/4671167/clustering.log)
Yes,Thanks for your help!

**Comment by wbaopaul** [comment]
Thanks. I guess the clustering was somehow not executed otherwise a seurat object file will be saved in .rds format or other type of error message would be through out . Here are few things I can think about: 
1) Did you run it on a linux cluster or HPC? I once got a similar error when I run the clustering module on HPC, but when I re-run the code the other day without changing any code, there was no error (don't know the reason). 

2) Do you got the same error on other matrix processed by scATAC-pro?  If you don't have another scATAC-pro format matrix, here you can download the processed matrix of 10x PBMC:
https://chopri.app.box.com/s/dlqybg6agug46obiu3mhevofnq4vit4t/folder/103920591038, you can give this data a try. 

3) If you installed scATAC-pro last week, I recommend install the new released version (there was a bug just corrected although I think it's not related to your error.)

Hope it helpful,
Thanks

**Comment by wbaopaul** [comment]
I’m closing this issue because it has been inactive for more than a month.

**Comment by sebboegel** [comment]
Dear @yejg2017,

if you did solve the issue, could you please let me know, how. I am running into the same problem. Find attached the log file.

@wbaopaul regarding your 3 points:
1.) not distributed, i have a closed VM
2.) I did try the matrixmtx file (544MB) provided, same error
3.) I have the latest version 1.3.1

Thanks Sebastian
[clustering.log](https://github.com/wbaopaul/scATAC-pro/files/6552169/clustering.log)

**Comment by wbaopaul** [comment]
@sebboegel Not sure of the reason. Are you using the latest version of configure_user.txt file? Can you post your configure_user.txt file as well (although I am not sure whether it related)? Thanks.

**Comment by sebboegel** [comment]
[configure_user.txt](https://github.com/wbaopaul/scATAC-pro/files/6568672/configure_user.txt)
I use the version of configure_user.txt file from v.1.3.0 and using scATAC pro v.1.3.1. 
I made edits with respect to mm10 and I made the cell calling parameters less stringent.

**Comment by wbaopaul** [comment]
Do you mind sharing the filtered matrix in .rds file? I will look into it. Thanks.

**Comment by sebboegel** [comment]
Thank you very much for your help. 
Attached the matrix.rds file found at output/filtered_matrix/MACS2/FILTER/matrix.rds
Note: i added the suffix ".txt" at the end of the file name, as i wasnt allowed to input ".rds". here

[matrix.rds.txt](https://github.com/wbaopaul/scATAC-pro/files/6589360/matrix.rds.txt)

**Comment by wbaopaul** [comment]
@sebboegel 
There could be two possibilities that result in the error:
1) Do you have a single cell qc file in output/summary/*.qc_per_barcode.txt file? This file is needed since the clustering module search and reads it and adds the qc metrics into the outputted seurat object (if you don't have this file it could need to error.  you can run qc_per_barcode to generate this file).   
2) There are only 60 cells in your matrix (which is too small in my experience ). When I ran tsne using the default setting there is an error (run tsne is included when you run scATAC-pro clustering module). If I skip tsne, it's fine and I got only one cluster finally. 
Hope it helps some!

**Comment by sebboegel** [comment]
Thanks a lot for your reply.

1.) I have a qc file in that folder. See attached.
2.) I repeated the analysis with less stringent filters in the MACS2 step and i repeated it with copying the raw matrix file into the filtered matrix folder, such that raw_matrix=filtered_matrix. However, i get the same issue.
[matrix.rds.txt](https://github.com/wbaopaul/scATAC-pro/files/6776908/matrix.rds.txt)
[MACS2.qc_per_barcode.txt.zip](https://github.com/wbaopaul/scATAC-pro/files/6776909/MACS2.qc_per_barcode.txt.zip)

**Comment by wbaopaul** [comment]
I can run your above data without any error using scATAC-pro v1.3.1. Here I attached the umap for your data.
[umap_clusters.eps.txt](https://github.com/wbaopaul/scATAC-pro/files/6785389/umap_clusters.eps.txt) (please remove .txt to view the .eps file).
Can you post your clustering.log file here?

**Comment by sebboegel** [comment]
You were able to completely run scATAC-pro with my matrix file without errors? So, i guess then there is nothing wrng with the input data, but rather with my software?
Here is the clustering.log file.
[clustering.log](https://github.com/wbaopaul/scATAC-pro/files/6789846/clustering.log)

**Comment by wbaopaul** [comment]
It seems there is problem of Seurat package. Probably your R seurat pacakge is too old? Not sure though, I would suggest to reinstall/upgrade your seurat package and/or upgrade scATAC-pro to the latest version (v1.4.0) or use singularity version.

**Comment by sebboegel** [comment]
You were totally right. I updated my R version to 4.1. in order to install the lastet seurat version. I also updated to the latest scATAC-pro version and the error disappears and i am able to move on. Thanks a lot

**Comment by wbaopaul** [comment]
Great!
