### ISSUE TITLE
Pbmc analysis takes very long

### ISSUE THREAD

**Issue by JihedC** [wbaopaul/scATAC-pro#17]
Hi @wbaopaul,

Thanks again for the pipeline! Since I have got an error with the fragment.txt last time I ran the pipeline for my samples without demultiplexing. I decided to work with the pbmc data from 10X as you suggested.
I am coming back to you because I think I have an issue with the `mapping` step. I am working with a slurm computer with the following parameters :

```
#SBATCH --time=150:00:00 # hh:mm:ss
#
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=15360 # 15G

```

The mapping step takes extremely long, I have obtained the mapping stats:  
```
Total_Pairs_Mapped    373728610
Total_Uniq_Mapped    341371537
Total_Mito_Mapped    1437951
Total_Dups    155996632
Total_Pairs_MAPQ30    334929001
Total_Mito_MAPQ30    1144820
Total_Dups_MAPQ30    144899955

```

But it's been 3 days that the same message is written in the log file:
```
Summarizing mapping stats ...
Simple mapping stats summary Done!
Getting txt file for read pair (fragment) information
```

But the fragment file is still empty.

So I have 2 questions, do you have suggestion on how to make the mapping faster on a cluster computer? and is it normal that the generation of the fragment.txt file takes so long in the pbmc dataset.

Thanks in advance for your help,

Jihed

**Comment by wbaopaul** [comment]
@JihedC Thanks for bringing up that issue. First, the mapping step shouldn't take that long for 10x pbmc data (a few hours for me). To save time, you may download [prebuilt mapping index](https://chopri.box.com/s/dlqybg6agug46obiu3mhevofnq4vit4t) and specify the index path in the configure file (otherwise it will prepare the index file which will take another few hours).  Second, it's also not normal to take so long to generate fragment.txt file. I never worked on a slurm system and not sure how it cooperates. To me, you need specify larger memory for the mapping step (15G is too small).

**Comment by JihedC** [comment]
Thanks for the quick reply.
I did generate the a bwa mapping index for hg38, it also took me a few hours :P and its path is in the configuration file. 
And thank you for the information of time, I will increase the memory.
