### ISSUE TITLE
Mapping error

### ISSUE THREAD

**Issue by sylestiel** [wbaopaul/scATAC-pro#25]
Hi

What does the following error mean? I'm running the script on a Virtual Machine via Mac terminal

Fri Jul 24 10:35:29 CDT 2020
Aligning ...
Starting alignment ... 
Fasta file not found: please specifie the .fa file path in the user configure file
Sorting bam file
[E::hts_open_format] Failed to open file output/mapping_result/P2_9.bam
samtools sort: can't open "output/mapping_result/P2_9.bam": No such file or directory
make: *** [mapping] Error 1

Thanks,

**Comment by wbaopaul** [comment]
You need genome .fa file and the index file to do read alignment, you can download them here:
https://chopri.app.box.com/s/dlqybg6agug46obiu3mhevofnq4vit4t 

suppose you are using hg38 genome assembly and bwa for alignment (then you can download the folder hg38_bwa_index in above link, where the .fa file and pre-built index files are given), you can specific the .fa file path in the configure_user.txt file like:
`BWA_INDEX=YOUR_DOWNLOAD_DIR_PATH/hg38_genome.fa`
This should solve your issue. Remember to keep the index files in the save folder of hg38_genome.fa, otherwise scATAC-pro will build bwa index files, which would take a few more hours.

**Comment by sylestiel** [comment]
Would I need to provide a path to both the rgtdata subfolder for mm10 and the mm10_bwa_index folder

**Comment by wbaopaul** [comment]
I don't think so. You just need to put the rgtdata folder under your home directory (in your case, the home dir of your VM I guess)  would be enough.

**Comment by sylestiel** [comment]
[configure_user.txt](https://github.com/wbaopaul/scATAC-pro/files/4973736/configure_user.txt)
<img width="197" alt="Screen Shot 2020-07-24 at 1 42 58 PM" src="https://user-images.githubusercontent.com/64283689/88424727-acca4a80-cdb3-11ea-829e-c25098f3ea24.png">


Still unable to run the mapping function

**Comment by sylestiel** [comment]
Should I be calling out a specific file within the bwa_index folder?
Does this file have to be within the executable folder?

**Comment by wbaopaul** [comment]
sorry, seems the .fa file was somehow missed. I just uploaded it to above folder.

**Comment by sylestiel** [comment]
The same error message is showing up despite uploading the missing file. Where should the bwa_mm10_index file reside?
In the executable folder  or in the home folder?
Please clarify if possible.

Thanks!
