### ISSUE TITLE
Error 137

### ISSUE THREAD

**Issue by Ping-lin14** [wbaopaul/scATAC-pro#34]
HI

When I used the fastq file to generate data, I encountered an error message
`BWA Mapping Done!`
`convert to bam ...`
`Converting sam to bam ...`
`Sorting bam file`
`/usr/local/bin/scATAC-pro_1.2.0/scripts/mapping.sh: line 31: 14506 Killed                  ${SAMTOOLS_PATH}/samtools sort -T ${mapRes_dir}/tmp/ -@ $ncore -n -o ${mapRes_dir}/${OUTPUT_PREFIX}.sorted.bam ${mapRes_dir}/${OUTPUT_PREFIX}.bam`
`make: *** [/usr/local/bin/scATAC-pro_1.2.0/scripts/Makefile:183: process] Error 137
`

The fastq files are generated using 10x genomics platform.
Is there any solution?

**Comment by wbaopaul** [comment]
Which platform are you using? I suppose you didn't run it on your own PC. I recommend to run the processing step on a linux server or HPC. The mapping step usually takes a large memory if your data sets are not small. I guess you don't have/specify enough memory for running the mapping step. Try to specify 100G memory typecially. (If possivle, please also let me know more details about how did you run it, like which commands and configure_user file.)

Hope it helps.

**Comment by Ping-lin14** [comment]
I am running on docker.

**Comment by Ping-lin14** [comment]
I use `scATAC-pro -s process -i 3234_scATACpro/ -c configure_user.txt -o output_3234 --verbose` to run.
Here is I my [configure_user.txt](https://github.com/wbaopaul/scATAC-pro/files/5919294/configure_user.txt) file.

**Comment by wbaopaul** [comment]
The way you run and the configure file looks OK. I am pretty sure the issue is from lack of memory of the docker version (thus killed). You may check the result under your output_3234/, the demultiplex and trimming step should work well. I have no solution for the memory issue of the docker version. Please use scATAC-pro on a linux server or HPC (you can also try the singularity version on a HPC if the singularity is installed there) which have enough memory.

**Comment by Ping-lin14** [comment]
Ok. Thank you very much for your answers.
I will try again.
