### ISSUE TITLE
Peak calling on Tn5 shifted fragment files

### ISSUE THREAD

**Issue by AnjaliC4** [wbaopaul/scATAC-pro#49]
Hi,

I realized that peak calling is done using bam files which are not shifted to adjust for Tn5 insertion. Therefore, if someone does the macs2 modeling of shift -100bp extsize 200bp, they may not get exactly the correct peaks. Please let me know if my understanding is naive, and if not, then could we have a work around this? I mean one option could be to convert bam to bed and shift them ? as macs2 accepts bed format. Please let me know your thoughts.

My another question, can the step scATAC-pro -s qc_per_barcode accept 10x cellranger generated fragment files?

Thanks very much,
Anjali

**Comment by wbaopaul** [comment]
Hi, you are right. The peak calling step ignored the Tn5 insertion. It can be easily fixed by shifting each of the calling peaks 4bp left and 5bp right. In scATAC-pro, since each peak was further extended to be 500 bp in length (from its mid-point) if the peak is shorten than 500bp,  the Tn5 insertion will only have very suble effect on downstream analysis. I would not worry about it. 

For the second question,  yes, you can use 10x cellrange genereated fragment.tsv.gz file.  But to be consistent, remember to use 10x cellrange generated fragment file for other modules (like get_mtx) if the fragment file is required.

Thanks

**Comment by AnjaliC4** [comment]
Hi, I deleted my previous comment about fragment files because I found a solution. However, I have a quick question about how the qc_per_barcode file is generated. The number of unique barcodes in the fragment file do not match the no. of barcodes present in qc_per_barcode.txt. I guess that the pipeline is "filtering barcodes with very low total uniq reads" I am not sure how this is calculated. Could you please confirm how the barcodes are getting filtered before qc_per_barcode file generation?  Please see that I used this step directly with 10x fragment file.
Thank you very much!

**Comment by wbaopaul** [comment]
When generating qc_per_barcode.txt file, to save memory usage, barcodes with less than or equal to 5 total unique framgents are removed since these barcodes are not useful for downstream analysis.
