### ISSUE TITLE
shifting ATAC-seq reads

### ISSUE THREAD

**Issue by haibol2016** [wbaopaul/scATAC-pro#59]
Hello Wenbao,

  I think the shifting operation of the ATAC-seq read end in scATAC-pro is not correct. (https://github.com/wbaopaul/scATAC-pro/blob/master/scripts/src/simply_bam2frags.pl#L73-L76). The shifting should consider the strand of read mapping, for reads mapped to the "+" and "-" strands, their end should be shift by  +4 and -5, respectively. By the way the code doesn't consider softclipping of the read ends due to low sequencing qulaity.

Haibo

**Comment by wbaopaul** [comment]
Hi Haibo, thanks for pointing out this issue. Since this only matters in a very few situation (like footprint analysis), I made the shifting be done optionally by turn a new parameter `SHIFT_READS_IN_BAM` in the configure_user.txt file to be "TRUE" (default FALSE) in the latest update in branch dev1.5.1. See https://github.com/wbaopaul/scATAC-pro/blob/dev1.5.1/scripts/mapping.sh#L51-L57. BTW, I'm not sure why we need to reconsider softclipping of the reads (since they have been handled in those popular aligner).
