### ISSUE TITLE
Duplicates not removed in positionsorted.MAPQ30.bam 

### ISSUE THREAD

**Issue by AnjaliC4** [wbaopaul/scATAC-pro#6]
Hi, 

Thank you for this tool and for answering my questions. It seems like the duplicates are marked but not removed after bwa mapping in positionsorted.MAPQ30.bam file which is suggested to be used for downstream analysis. In your mapping.sh file, I noticed command for removing duplicates was written as a comment. Any reasons for this? Is positionsorted.mapq30.bam without removing duplicates good enough for peak and cell calling? Thank you very much!

**Comment by wbaopaul** [comment]
I think it's better to keep the duplicates since the duplicates will be used when preparing the fragment.txt file and marked in fragment.txt file anyway. The peak calling tool such as MACS2 can handle bam file with duplicates. Cell calling works on unique fragments using fragment.txt file.  Therefore, both peak and cell calling are not affected by keeping the duplicates in the bam file while keeping more infromation.

**Comment by AnjaliC4** [comment]
OK thank you very much.
