### ISSUE TITLE
`downstream_analysis/MACS2/FILTER/seurat_obj.rds` not found

### ISSUE THREAD

**Issue by aseyedia** [wbaopaul/scATAC-pro#64]
Hi Wenbao,

Hope you are well. I am using v1.5.1 on many samples, and I'm using both `scATAC-pro process` and `scATAC-pro downstream`.  The process step works fine but unfortunately, none of my samples can make it past the downstream step: 

```
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/mnt/isilon/cscb/Projects/10x/dingy/ding_scRNA_ATACseq_PhALL/scATAC-pro_singularity/day_3_scATACpro/NH011_Das_day_3/downstream_analysis/MACS2/FILTER/seurat_obj.rds', probable reason 'No such file or directory'
Execution halted
/usr/local/bin/scATAC-pro_1.5.1/scripts/clustering.sh: line 32: /mnt/isilon/cscb/Projects/10x/dingy/ding_scRNA_ATACseq_PhALL/scATAC-pro_singularity/day_3_scATACpro/NH011_Das_day_3/downstream_analysis/MACS2/FILTER/VisCello_obj/config.yml: No such file or directory
/usr/local/bin/scATAC-pro_1.5.1/scripts/clustering.sh: line 33: /mnt/isilon/cscb/Projects/10x/dingy/ding_scRNA_ATACseq_PhALL/scATAC-pro_singularity/day_3_scATACpro/NH011_Das_day_3/downstream_analysis/MACS2/FILTER/VisCello_obj/config.yml: No such file or directory
/usr/local/bin/scATAC-pro_1.5.1/scripts/clustering.sh: line 34: /mnt/isilon/cscb/Projects/10x/dingy/ding_scRNA_ATACseq_PhALL/scATAC-pro_singularity/day_3_scATACpro/NH011_Das_day_3/downstream_analysis/MACS2/FILTER/VisCello_obj/config.yml: No such file or directory
/usr/local/bin/scATAC-pro_1.5.1/scripts/clustering.sh: line 35: /mnt/isilon/cscb/Projects/10x/dingy/ding_scRNA_ATACseq_PhALL/scATAC-pro_singularity/day_3_scATACpro/NH011_Das_day_3/downstream_analysis/MACS2/FILTER/VisCello_obj/config.yml: No such file or directory
/usr/local/bin/scATAC-pro_1.5.1/scripts/clustering.sh: line 36: /mnt/isilon/cscb/Projects/10x/dingy/ding_scRNA_ATACseq_PhALL/scATAC-pro_singularity/day_3_scATACpro/NH011_Das_day_3/downstream_analysis/MACS2/FILTER/VisCello_obj/config.yml: No such file or directory
/usr/local/bin/scATAC-pro_1.5.1/scripts/clustering.sh: line 37: /mnt/isilon/cscb/Projects/10x/dingy/ding_scRNA_ATACseq_PhALL/scATAC-pro_singularity/day_3_scATACpro/NH011_Das_day_3/downstream_analysis/MACS2/FILTER/VisCello_obj/config.yml: No such file or directory
make: *** [/usr/local/bin/scATAC-pro_1.5.1/scripts/Makefile:273: downstream] Error 1
```

It seems to indicate that clustering step is encountering an error because the results of VisCello processing are not found, even though in my config file, I have set `prepCello = TRUE  ## generate object for VisCello (for visualization)`.

Just letting you know that I am encountering this error. Let me know if there are any config arguments that I could possibly change to circumvent this.

Thank you,
Arta

**Comment by wbaopaul** [comment]
Can you check the log file for the clustering step? It seems there is something wrong there and it couldn't generate the seurat object. Hope this helps!

**Comment by aseyedia** [comment]
The only other error I see in the log file other than what I already showed you is this:

```
Error in fread(feature_path, header = F) : 
  File 'day_3_scATACpro/NH011_Das_day_3/output/filtered_matrix/MACS2/FILTER/features.txt' does not exist or is non-readable. getwd()=='/mnt/isilon/cscb/Projects/10x/dingy/ding_scRNA_ATACseq_PhALL/scATAC-pro_singularity'
Calls: read_mtx_scATACpro -> fread
```

which is weird, because there's definitely a `features` file in that directory, just doesn't have the `.txt` extension...

Does it have to do with the `cleanenv` argument? Here are my calls:

```
singularity exec \
  --bind /mnt/isilon/ \
  --cleanenv -H /mnt/isilon/cscb/Projects/10x/dingy/ding_scRNA_ATACseq_PhALL/ \
  /mnt/isilon/cscb/Projects/10x/dingy/ding_scRNA_ATACseq_PhALL/scATAC-pro_singularity/scatac-pro_latest.sif \
    scATAC-pro --step process \
      -i $FASTQ_DIR \
      -o "$time_point_folder/$sample_time_point" \
      -c $configure_file --verbose
      
echo "Let's do some scATAC-pro downstream analyses"

singularity exec \
  --bind /mnt/isilon/ \
  --cleanenv -H /mnt/isilon/cscb/Projects/10x/dingy/ding_scRNA_ATACseq_PhALL/ \
  /mnt/isilon/cscb/Projects/10x/dingy/ding_scRNA_ATACseq_PhALL/scATAC-pro_singularity/scatac-pro_latest.sif \
    scATAC-pro --step downstream \
      -i $time_point_folder/$sample_time_point/output/filtered_matrix/MACS2/FILTER/matrix.mtx \
      -o "$time_point_folder/$sample_time_point" \
      -c $configure_file --verbose
```

**Comment by wbaopaul** [comment]
Seems there was some issue of file path. Please examine your output file path of the process step and input file path of the downstream step. Use full path is generally recommended!

**Comment by aseyedia** [comment]
You're right, I think the `output` subdirectory was extraneous. My mistake, thank you Wenbao.

**Comment by khushi0810** [comment]
Hello Wenbao @wbaopaul ,

I am also using v1.5.1 on one of my samples , and I'm using scATAC-pro reprocess because I have my bam files from cell ranger and scATAC-pro downstream . I am also encountering the same error as @aseyedia. 

I am running on HPC as a batch job. I am attaching my log file , configure file as well as my script for you reference. 

Any suggestions are highly appreciated. 

Thank you 
Khushi 
[reprocess_cellranger_output.log](https://github.com/wbaopaul/scATAC-pro/files/14474453/reprocess_cellranger_output.log)

[configure_user.txt](https://github.com/wbaopaul/scATAC-pro/files/14474456/configure_user.txt)

#####################################

module load singularity/3.9.9

cd /project/bioinformatics/JLee_lab/s227606/scATAC/NONP

singularity exec --bind /project/bioinformatics/JLee_lab/s227606/scATAC -H /project/bioinformatics/JLee_lab/s227606/scATAC/NONP --cleanenv /project/bioinformatics/JLee_lab/s227606/scATAC/NONP/scatac-pro_latest.sif scATAC-pro -s reprocess_cellranger_output -i /project/bioinformatics/JLee_lab/s227606/scATAC/files/BL51_NP/outs/possorted_bam.bam,/project/bioinformatics/JLee_lab/s227606/scATAC/files/BL51_NP/outs/fragments.tsv.gz -c /project/bioinformatics/JLee_lab/s227606/scATAC/configure_user.txt

singularity exec --bind /project/bioinformatics/JLee_lab/s227606/scATAC -H /project/bioinformatics/JLee_lab/s227606/scATAC/NONP --cleanenv /project/bioinformatics/JLee_lab/s227606/scATAC/NONP/scatac-pro_latest.sif scATAC-pro -s downstream -i /project/bioinformatics/JLee_lab/s227606/scATAC/NONP/output/filtered_matrix/MACS2/FILTER/matrix.mtx -c /project/bioinformatics/JLee_lab/s227606/scATAC/configure_user.txt

###################################################
